version: '3.7'

services:
   php-httpd:
      image: php:8.1-apache
      ports:
         - 83:80
      volumes:
         - "./DocumentRoot:/var/www/html"

   # Necessari per tenir mysqli sense crear imatge pròpia
      command: "/bin/sh -c 'docker-php-ext-install mysqli && exec apache2-foreground'" 
         
   mariadb:
      image: mariadb:10.6
      volumes:
        - "./database:/var/lib/mysql"
      environment:
        TZ: "Europe/Madrid"
        MYSQL_ROOT_PASSWORD: "MirMeetCool12"
        MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        MYSQL_USER: 'r00t'
        MYSQL_PASSWORD: 'r00t'
        MYSQL_DATABASE: 'pymeralias2'

   phpmyadmin:
      image: phpmyadmin
      ports:
        - 8084:80
      links:
        - 'mariadb:db'
         
   node:
      image: node
      tty: true